# config.yaml

# SETTINGS
LIMITS:
  REQUESTS: 15
  WINDOW_SECONDS: 60


# SKINS
TRACKING_ITEMS:
  - market_hash_name: "Revolution Case"
    appid: 730
    currency: '$'
    country: 'US'
    language: 'english'
    polling-interval-in-seconds: 30
    apiid: 'priceoverview'

  - market_hash_name: "AK-47 | Nightwish (Field-Tested)"
    appid: 730
    currency: '$'
    country: 'NL'
    language: 'english'
    polling-interval-in-seconds: 15
    apiid: 'priceoverview' 
  
  - market_hash_name: "Dreams & Nightmares Case"
    appid: 730
    currency: 1  # 1 = USD
    country: 'US'
    language: 'english'
    polling-interval-in-seconds: 30
    apiid: 'itemordershistogram' 
  
  - market_hash_name: "MP9 | Starlight Protector (Field-Tested)"
    appid: 730
    currency: 1  # 1 = USD
    country: 'US'
    language: 'english'
    polling-interval-in-seconds: 15
    apiid: 'itemordershistogram' 