# config.yaml

# SETTINGS
LIMITS:
  REQUESTS: 15
  WINDOW_SECONDS: 60


# SKINS
TRACKING_ITEMS:
  - market_hash_name: "AWP | Dragon Lore (Factory New)"
    appid: 730
    currency: '$'
    country: 'US'
    language: 'english'
    polling-interval-in-seconds: -1
    apiid: 'pricehistory'

  - market_hash_name: "AK-47 | Redline (Field-Tested)"
    appid: 730
    currency: '$'
    country: 'NL'
    language: 'english'
    polling-interval-in-seconds: 20
    apiid: 'priceoverview' 
  
  - market_hash_name: "AWP | Neo-Noir (Factory New)"
    appid: 730
    currency: 1  # 1 = USD
    country: 'US'
    language: 'english'
    polling-interval-in-seconds: 60
    apiid: 'itemordershistogram' 
  
  - market_hash_name: "AK-47 | Redline (Field-Tested)"
    item_nameid: 7178002
    appid: 730
    currency: 1  # 1 = USD
    country: 'US'
    language: 'english'
    polling-interval-in-seconds: 60
    apiid: 'itemordersactivity' 