# config.yaml

# SETTINGS
LIMITS:
  REQUESTS: 15
  WINDOW_SECONDS: 60


# SKINS
TRACKING_ITEMS:
  - market_hash_name: "M4A4 | Magnesium (Minimal Wear)"
    appid: 730
    currency: '$'
    country: 'US'
    language: 'english'
    polling-interval-in-seconds: 1
    apiid: 'priceoverview'

  - market_hash_name: "AK-47 | Fire Serpent (Field-Tested)"
    appid: 730
    currency: '$'
    country: 'NL'
    language: 'english'
    polling-interval-in-seconds: 2
    apiid: 'priceoverview' 
  
  - market_hash_name: "AWP | Neo-Noir (Factory New)"
    appid: 730
    currency: 1  # 1 = USD
    country: 'US'
    language: 'english'
    polling-interval-in-seconds: 5
    apiid: 'itemordershistogram' 
  
  - market_hash_name: "AK-47 | Redline (Field-Tested)"
    appid: 730
    currency: 1  # 1 = USD
    country: 'US'
    language: 'english'
    polling-interval-in-seconds: 9
    apiid: 'itemordersactivity' 